// <auto-generated />
using System;
using FutbolBack.DataContex;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FutbolBack.Migrations
{
    [DbContext(typeof(FutbolDbContext))]
    partial class FutbolDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FutbolBack.Modelos.Entrenador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId")
                        .IsUnique();

                    b.ToTable("Entrenadores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EquipoId = 1,
                            Nombre = "Pep Guardiola"
                        },
                        new
                        {
                            Id = 2,
                            EquipoId = 2,
                            Nombre = "Carlo Ancelotti"
                        });
                });

            modelBuilder.Entity("FutbolBack.Modelos.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estadio")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Equipos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estadio = "Camp Nou",
                            Nombre = "Barcelona"
                        },
                        new
                        {
                            Id = 2,
                            Estadio = "Santiago Bernabéu",
                            Nombre = "Real Madrid"
                        });
                });

            modelBuilder.Entity("FutbolBack.Modelos.Jugador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Equipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Posicion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Jugadores");
                });

            modelBuilder.Entity("FutbolBack.Modelos.Liga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Ligas");
                });

            modelBuilder.Entity("FutbolBack.Modelos.Partido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipoLocalId")
                        .HasColumnType("int");

                    b.Property<int>("EquipoVisitanteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("EquipoLocalId");

                    b.HasIndex("EquipoVisitanteId");

                    b.ToTable("Partidos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EquipoLocalId = 1,
                            EquipoVisitanteId = 2,
                            Fecha = new DateTime(2024, 10, 19, 21, 11, 40, 159, DateTimeKind.Local).AddTicks(2801)
                        },
                        new
                        {
                            Id = 2,
                            EquipoLocalId = 2,
                            EquipoVisitanteId = 1,
                            Fecha = new DateTime(2024, 10, 24, 21, 11, 40, 159, DateTimeKind.Local).AddTicks(2819)
                        });
                });

            modelBuilder.Entity("FutbolBack.Modelos.Entrenador", b =>
                {
                    b.HasOne("FutbolBack.Modelos.Equipo", "Equipo")
                        .WithOne("Entrenador")
                        .HasForeignKey("FutbolBack.Modelos.Entrenador", "EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("FutbolBack.Modelos.Partido", b =>
                {
                    b.HasOne("FutbolBack.Modelos.Equipo", "EquipoLocal")
                        .WithMany("PartidosLocal")
                        .HasForeignKey("EquipoLocalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FutbolBack.Modelos.Equipo", "EquipoVisitante")
                        .WithMany("PartidosVisitante")
                        .HasForeignKey("EquipoVisitanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquipoLocal");

                    b.Navigation("EquipoVisitante");
                });

            modelBuilder.Entity("FutbolBack.Modelos.Equipo", b =>
                {
                    b.Navigation("Entrenador");

                    b.Navigation("PartidosLocal");

                    b.Navigation("PartidosVisitante");
                });
#pragma warning restore 612, 618
        }
    }
}
